### ISSUE TITLE
Please export array-index-row-major

### ISSUE THREAD

**Issue by ILoveGoulash** [Lisp-Stat/array-operations#3]
Title says it all, it can be useful to others.

**Comment by ashpool37** [comment]
Since `array-index-row-major` does not actually need the contents of the array to work, I suggest re-implementing it in terms of a new function that instead of accepting an array as an argument would directly accept a list of dimensions. One or both of those functions can then be exported if desired. This would allow for more flexibility in case the actual array object isn't there.

```common-lisp
(defun row-major-to-index (dimensions rmi &optional result)
  ;; the present implementation of `array-index-row-major`, slightly modified
)

(defun array-index-row-major (array rmi &optional result)
  (row-major-to-index
    (array-dimensions array)  ; or whatever it actually does
    rmi result))
```
